name: CI

on:
  push:
    branches: [ master,master3,development, feature/* ]

  pull_request:
    branches:
      - development
      - master3
      - master

jobs:
  ci:
    runs-on: [ ubuntu-latest ]


    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'


      - name: run unittest
        run: |
          chmod=+x gradlew
          ./gradlew clean test
